Homework1
DarkLordXXX/task1 pull request #1
Opened 2024-08-19 15:47 UTC by DarkLordXXX

Тут з 1 по 4 завдання 1 уроку

2024-08-19 16:24 UTC, prokopiff requested changes

2024-08-19 16:24 UTC, prokopiff commented on src/Lesson1/Homework1.java
> +        int a4 = 077;
Тут нема _усіх можливих систем числень для кожного типу_
Є для інта тільки.

2024-08-19 16:24 UTC, prokopiff commented on src/Lesson1/Homework1.java
> +        int sumChar = 7;
Тут не суми, а просто літерали якісь.

2024-08-19 16:24 UTC, prokopiff commented on src/Lesson1/Homework2.java
> +    public static double convertCelsiusToFahrenheit(double celsius) {
Не використаний параметр методу

2024-08-19 16:24 UTC, prokopiff commented on src/Lesson1/Homework2.java
> +        return TempCelcius;
Неправильний формат імен змінних
https://www.oracle.com/technetwork/java/codeconventions-150003.pdf

2024-08-20 13:28 UTC, DarkLordXXX commented on src/Lesson1/Homework1.java
> +        int a4 = 077;
Поправив.

2024-08-20 13:29 UTC, DarkLordXXX commented on src/Lesson1/Homework1.java
> +        int sumChar = 7;
Поміняв.

2024-08-20 13:39 UTC, prokopiff requested changes

2024-08-20 13:39 UTC, prokopiff commented on src/Lesson1/Homework1.java
> +        System.out.println(c1+" "+c2+" "+c3+" "+c4+" тут чари");
Виправити форматування у кожному із цих рядків, прибрати зайві дужки.

2024-08-20 13:41 UTC, prokopiff commented on src/Lesson1/Homework1.java
> +        //sumChar, та присвоїти їм значення суми свіх раніше створенних змінних відповідного типу.
Зручно, що є умови завдань, ще би вони завжди йшли перед рішеннями

2024-08-21 07:59 UTC, DarkLordXXX commented on src/Lesson1/Homework1.java
> +        System.out.println(c1+" "+c2+" "+c3+" "+c4+" тут чари");
Поправив, забрав

2024-08-21 07:59 UTC, DarkLordXXX commented on src/Lesson1/Homework1.java
> +        //sumChar, та присвоїти їм значення суми свіх раніше створенних змінних відповідного типу.
Поставив зверху.

2024-08-21 08:25 UTC, prokopiff requested changes

2024-08-21 08:25 UTC, prokopiff commented on src/Lesson1/Homework1.java
> +        // тепер знаю що флоати і дабли не підтримують двійкову і вісімкову системи числення
Це не зовсім коректне твердження, бо вони теж використовують двійкову, як і все решта в комп'ютерах, просто ми не маємо способу їх так записувати в коді.

Але є додатковий спосіб, який можна було використати:
```java
double d = 15e-3;
```

2024-08-21 08:25 UTC, prokopiff commented on src/Lesson1/Homework2.java
> +    public static double convertCelsiusToFahrenheit(double celsius) {
Бракує порожнього рядка між методами.

2024-08-21 19:02 UTC, prokopiff commented on src/Lesson1/Homework2.java
> +        return TempCelcius;
Це все ще актуально. Все решта вже ок

2024-08-21 19:15 UTC, prokopiff commented on src/Lesson1/Homework3.java
> +        double Inches = centimetres * 2.54;
Назва цієї змінної не відповідає конвеншинам, а ще вона бреше, бо результат є сантиметрами насправді. Те саме із параметром методу

2024-08-23 16:21 UTC, prokopiff commented on src/Lesson1/Homework3.java
> +        System.out.println(centimetres+ "  сантиметрам");;
Тут ще варто `double` використати і виправити кількість пробілів навколо операторів

2024-08-30 16:11 UTC, prokopiff approved these changes

2024-08-30 16:11 UTC, artbelmeha approved these changes

2024-09-06 15:36 UTC, merged