Lesson2
DarkLordXXX/task1 pull request #2
Opened 2024-08-30 15:31 UTC by DarkLordXXX

Тут 2 урок з 1-8 завдання. Має працювати добре, Все провіряв. Останне 9 не зробив не вкурсі що то за Амстронг тикий.

2024-08-30 15:49 UTC, artbelmeha requested changes

2024-08-30 15:49 UTC, artbelmeha commented on src/Lesson1/Homework1.java
> +        //  1.1  Створити змінні примітивних типів, усіх можливих систем числень для кожного типу.\
бекслеш в кінці зайвий

2024-08-30 15:49 UTC, artbelmeha commented on src/Lesson1/Homework1.java
> +        byte b4 = 012; // вісімкова система
ці коментарі не потрібні

2024-08-30 15:49 UTC, artbelmeha commented on src/Lesson1/Homework1.java
> +        double result2 = sumDouble + sumFloat;
результат потрібно було записати в одну змінну

2024-08-30 15:49 UTC, artbelmeha commented on src/Lesson1/Homework1.java
> +        System.out.println(result2 + " тут дабли і флоати");
і тут поправити

2024-08-30 15:49 UTC, artbelmeha commented on src/Lesson1/Homework2.java
> +    }
зразу повертати результат

2024-08-30 15:49 UTC, artbelmeha commented on src/Lesson2/home1.java
> +        int sum5 = a1 % a2;
чому змінні називаються sum..

2024-08-30 15:49 UTC, artbelmeha commented on src/Lesson2/home2.java
> +
а чому треба в аппер кейс?

2024-08-30 15:49 UTC, artbelmeha commented on src/Lesson2/home3.java
> +            System.out.println("Тут кінець програми ...+ _ +");
чому кінець? тут інший результат...

2024-08-30 15:49 UTC, artbelmeha commented on src/Lesson2/home4.java
> +        }
запусти програму перевір що виведе

2024-08-30 15:49 UTC, artbelmeha commented on src/Lesson2/home5.java
> +        System.out.println("Сума цифр: " + sum);
не то зроблено сума цифр числа: число 125 -> 1 + 2 + 5 = 8

2024-08-30 15:49 UTC, artbelmeha commented on src/Lesson2/home6.java
> +        System.out.println("Факторіал числа " + number + " дорівнює " + factorial);
це не то, ось проглянь що треба: https://uk.wikipedia.org/wiki/%D0%A4%D0%B0%D0%BA%D1%82%D0%BE%D1%80%D1%96%D0%B0%D0%BB

2024-08-30 15:49 UTC, artbelmeha commented on src/Lesson2/home7.java
> +        System.out.println("Відстань мінь між кординатами у-гриків : " + sum2);
і тут не то

2024-08-30 15:59 UTC, DarkLordXXX commented on src/Lesson1/Homework1.java
> +        //  1.1  Створити змінні примітивних типів, усіх можливих систем числень для кожного типу.\
Забрав.

2024-08-30 15:59 UTC, DarkLordXXX commented on src/Lesson1/Homework1.java
> +        byte b4 = 012; // вісімкова система
Почистив.

2024-08-30 16:01 UTC, prokopiff requested changes
Код у пакеті Lesson1 я дивитись не буду, бо він з попереднього PR

2024-08-30 16:01 UTC, prokopiff commented on src/Lesson2/home1.java
> +        int sum5 = a1 % a2;
Це все не суми

2024-08-30 16:01 UTC, prokopiff commented on src/Lesson2/home1.java
> +public class home1 {
https://www.oracle.com/technetwork/java/codeconventions-150003.pdf

2024-08-30 16:01 UTC, prokopiff commented on src/Lesson2/home2.java
> +public class home2 {
https://www.oracle.com/technetwork/java/codeconventions-150003.pdf

2024-08-30 16:01 UTC, prokopiff commented on src/Lesson2/home2.java
Якщо це саме те, що малося на увазі в завданні, то інших проблем не бачу, крім граматичних і орфографічних помилок у коментах.

2024-08-30 16:01 UTC, prokopiff commented on src/Lesson2/home3.java
> +public class home3 {
https://www.oracle.com/technetwork/java/codeconventions-150003.pdf

2024-08-30 16:01 UTC, prokopiff commented on src/Lesson2/home3.java
> +        }
А воно не скаже, якщо числа рівні?
До речі, це було б простіше із цілими числами. І хороший привід пошукати, як краще порівнювати float i double на рівність, бо із цим бувають проблеми

2024-08-30 16:01 UTC, prokopiff commented on src/Lesson2/home4.java
> +public class home4 {
https://www.oracle.com/technetwork/java/codeconventions-150003.pdf

2024-08-30 16:01 UTC, prokopiff commented on src/Lesson2/home4.java
> +            System.out.println("сума перших 10 числел :" + sum);
Запусти код і виправи проблему тут.

2024-08-30 16:01 UTC, prokopiff commented on src/Lesson2/home5.java
> +public class home5 {
https://www.oracle.com/technetwork/java/codeconventions-150003.pdf

2024-08-30 16:01 UTC, prokopiff commented on src/Lesson2/home5.java
> +        System.out.println("Сума цифр: " + sum);
Цей код робить зовсім не те, що написано в умові на рядку 7

2024-08-30 16:01 UTC, prokopiff commented on src/Lesson2/home6.java
> +public class home6 {
https://www.oracle.com/technetwork/java/codeconventions-150003.pdf

2024-08-30 16:01 UTC, prokopiff commented on src/Lesson2/home6.java
> +        System.out.println("Факторіал числа " + number + " дорівнює " + factorial);
Це правильний алгоритм обрахування факторіала, але в джаві він видає правильний результат тільки для чисел менших за 21. Хороша нагода пошукати, як зробити краще.

2024-08-30 16:01 UTC, prokopiff commented on src/Lesson2/home7.java
> +public class home7 {
https://www.oracle.com/technetwork/java/codeconventions-150003.pdf

2024-08-30 16:01 UTC, prokopiff commented on src/Lesson2/home7.java
> +        int sum2 = y1 - y2;
1. Це не суми
2. Відстань між точками із координатами (x1, y1) i (x2, y2) на площині рахується не так.

2024-08-30 16:01 UTC, prokopiff commented on src/Lesson2/home8.java
> +public class home8 {
https://www.oracle.com/technetwork/java/codeconventions-150003.pdf

2024-08-30 16:01 UTC, prokopiff commented on src/Lesson2/home8.java
> +            int secondNumber = number % 10;
Це не second (бо last), і не number (бо digit).

2024-08-30 16:43 UTC, DarkLordXXX commented on src/Lesson2/home3.java
> +            System.out.println("Тут кінець програми ...+ _ +");
Поправив.

2024-08-30 16:48 UTC, DarkLordXXX commented on src/Lesson1/Homework1.java
> +        double result2 = sumDouble + sumFloat;
Зробив у одну змінну result3.

2024-08-30 19:13 UTC, DarkLordXXX commented on src/Lesson2/home4.java
> +        }
Поправив. Тепер те що треба.

2024-08-30 19:15 UTC, DarkLordXXX commented on src/Lesson2/home4.java
> +        }
Поправив.

2024-08-30 19:15 UTC, DarkLordXXX commented on src/Lesson2/home7.java
> +        System.out.println("Відстань мінь між кординатами у-гриків : " + sum2);
Поправив довго шукав і знайшов.

2024-08-30 19:16 UTC, DarkLordXXX commented on src/Lesson2/home1.java
> +        int sum5 = a1 % a2;
Поправив назви змінних.

2024-08-31 08:15 UTC, artbelmeha commented on src/Lesson1/Homework1.java
> +        double result2 = sumDouble + sumFloat;
подивись на рядок 45 що у завданні просили

2024-08-31 08:19 UTC, artbelmeha commented on src/Lesson2/home4.java
> +        for(i = 1; i <= num; ++i)
поправ ці два рядка, `i` потрібно об'являти в `for`, a `num` взагалі не треба створювати як змінну, ти використовуєш її один раз

2024-08-31 08:19 UTC, artbelmeha commented on src/Lesson2/home4.java
> +        for(i = 1; i <= num; ++i)
і формутвання поправ

2024-08-31 08:20 UTC, artbelmeha commented on src/Lesson2/home7.java
> +    public static double distance_Between_LatLong(double lat1, double lon1, double lat2, double lon2) {
що це за дивна назва методу?

2024-08-31 08:23 UTC, artbelmeha commented
Загалом непогано, мінорні коментарі. Якщо сам все робиш то прогрес є, хоч і досить повільний. Продовжуй працювати!

2024-09-02 04:24 UTC, artbelmeha commented on src/Lesson1/Homework1.java
> +        long result3 = result1 + (long)result2;//Тепер приймає як лонг.
тут пробіл треба після `(long)`

2024-09-03 14:40 UTC, prokopiff commented on src/Lesson2/home5.java
> +        int number, digit, sum = 0;
Ще це треба виправити. Так робити не можна, хоча компілятор і дозволяє

2024-09-03 15:09 UTC, prokopiff commented on src/Lesson2/home4.java
Тут щось пішло не так

2024-09-03 15:10 UTC, prokopiff commented on src/Lesson2/home5.java
> +        int number, digit, sum = 0;
Цей комент насправді ще не виправлений, хоча GitHub  пише Outdated

2024-09-06 15:36 UTC, merged